# This file can be used to install module dependencies for unit testing
# See https://github.com/puppetlabs/puppetlabs_spec_helper#using-fixtures for details
---
fixtures:
  forge_modules:
    stdlib:
      repo: puppetlabs/stdlib
      ref: 4.25.1
    firewall:
      repo: puppetlabs/firewall
      ref: 1.12.0
    firewalld:
      repo: crayfishx/firewalld
      ref: 3.4.0
